In [1]:
import pandas as pd

In [3]:
df1=pd.read_csv('datasets/dataset1_text_rich_transactions.csv')
df1.head()

,transaction_id,transaction_date,amount,currency,description,vendor_name,gst_applicable,gst_slab,itc_eligible,category_label,is_anomaly
0,TXN0000001,01-04-2024,7641.92,INR,imps ikea rcpt/2404/001 subs - office supplies...,IKEA,True,12%,TRUE,Office Supplies,0
1,TXN0000002,01-04-2024,58560.14,INR,upi awfis rcpt/2404/002 fy24 - rent exp# ref ...,Awfis,True,18%,TRUE,Rent,0
2,TXN0000003,01-04-2024,2184.95,INR,/ imps zomato inv/2404/003 q2 - meals exp,ZOMATO,True,5%,FALSE,Meals,0
3,TXN0000004,01-04-2024,5375.79,INR,*CARD OFFICE DEPOT Pvt Ltd INV/2404/004 FY25 -...,OFFICE DEPOT Pvt Ltd,True,12%,TRUE,Office Supplies,0
4,TXN0000005,01-04-2024,68830.10,INR,-UPI AWFIS INDIA PVT LTD TAXINV/2404/005 RENT ...,AWFIS INDIA PVT LTD,True,18%,TRUE,Rent,0

In [4]:
df2=pd.read_csv('datasets/dataset2_non_text_transactions.csv')
df2.head()

,transaction_id,transaction_date,amount,currency,vendor_id,gst_applicable,gst_slab,itc_eligible,is_anomaly
0,NTX0000001,01-04-2024,2016.36,INR,V0033,True,5%,FALSE,0
1,NTX0000002,01-04-2024,8530.60,INR,V0005,True,18%,TRUE,0
2,NTX0000003,01-04-2024,33181.64,INR,V0014,True,18%,TRUE,0
3,NTX0000004,01-04-2024,14510.68,INR,V0004,True,18%,TRUE,0
4,NTX0000005,01-04-2024,4667.38,INR,V0021,True,5%,FALSE,0